config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "projects#index"

  resources :projects
  post '/update_recommendation' => 'projects#update_recommendation', :as => :update_recommendation

  namespace :contractor do
    resources :general_contractors
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/general_contractor.rb
class GeneralContractor < ApplicationRecord
  has_many :project_recommendations, :class_name => "ProjectContractorRelation"
  has_many :projects, through: :project_recommendations

  validates_presence_of :name, :longitude, :latitude,:maximum_budget_willing, :minimum_budget_willing
  validates_uniqueness_of :name
  validates :maximum_budget_willing,:maximum_budget_willing , format: { with: /\A\d+\z/, message: "Integer only. No sign allowed." }
  #validate :range_limit

  private
  def range_limit
    if maximum_budget_willing < minimum_budget_willing
      errors.add(:maximum_budget_willing, "cannot be less than minimum budget willing")
    end
  end

end

app/models/project.rb
class Project < ApplicationRecord
  has_many :contractor_recommendations, :class_name => "ProjectContractorRelation"
  has_many :general_contractors, through: :contractor_recommendations

  validates_presence_of :name, :longitude, :latitude, :maximum_budget, :minimum_budget
  validates_uniqueness_of :name #assuming name of project is unique handle of the project

end

app/models/project_contractor_relation.rb
class ProjectContractorRelation < ApplicationRecord
  belongs_to  :project
  belongs_to :general_contractor

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contractor/general_contractors_controller.rb
class Contractor::GeneralContractorsController < ApplicationController
  layout 'contractor_layout'

  before_action :set_general_contractor, only: [:show, :edit, :update]

  def index
    @general_contractors = GeneralContractor.all
    respond_to do |format|
      format.html  # index.html.erb
      format.json  { render :json => @general_contractors }
    end
  end

  def new
    @general_contractor = GeneralContractor.new
  end

  def create
    validate_create_request
    @general_contractor = GeneralContractor.new(contractor_params)
    @general_contractor.save!

    respond_to do |format|
      format.html { redirect_to contractor_general_contractor_path(@general_contractor), notice: 'Contractor created successfully.' }
      format.json  { render :json => @general_contractor }
    end
  rescue Exception => e
    subject = "Error: Exception in GeneralContractorsController#create. Msg => #{ e.message }."
    details =  params.inspect
    logger.error (subject + details)
    redirect_to new_contractor_general_contractor_path, :alert => e.message
  end

  def show
    @project_recommended =  @general_contractor.project_recommendations.where(project_owner_accepted: true)
  end

  def edit
  end

  def update
    validate_create_request
    respond_to do |format|
      if @general_contractor.update_attributes(contractor_params)
        format.html { redirect_to edit_contractor_general_contractor_path(@general_contractor), notice: 'Contractor was successfully updated.' }
      else
        format.html { render :edit }
      end
    end

  rescue Exception => e
    subject = "Error: Exception in GeneralContractorsController#update. Msg => #{ e.message }."
    details =  params.inspect
    logger.error (subject + details)

    redirect_to edit_contractor_general_contractor_path(@general_contractor), :alert => e.message
  end


  private

  def validate_create_request
    ExceptionUtils.check_if(params[:general_contractor][:maximum_budget_willing].to_i >= params[:general_contractor][:minimum_budget_willing].to_i,
                            'Maximum budget willing cannot be less than minimum budget willing.')

    ExceptionUtils.check_if(params[:general_contractor][:design_services_offered] == '1' || params[:general_contractor][:build_services_offered] == '1',
                            'At-least one service should be chosen for the project.')

  end

  def set_general_contractor
    @general_contractor = GeneralContractor.find(params[:id])
    raise Exception.new("Project with #{params[:id]} not found") if @general_contractor.nil?
  end

  def contractor_params
    params.require(:general_contractor).permit(:id ,:name,:latitude,:longitude, :maximum_budget_willing, :minimum_budget_willing, :design_services_offered,
                                    :build_services_offered
    )
  end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update]

  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @projects }
    end
  end

  def new
    @project = Project.new
  end

  def create
    validate_create_request
    @project = Project.new(project_params)
    @project.save!

    respond_to do |format|
      format.html { redirect_to project_path(@project), notice: 'Project was successfully created.' }
      format.json { render :json => @projects }
    end

  rescue Exception => e
    subject = "Error: Exception in project#create. Msg => #{ e.message }."
    details = params.inspect
    logger.error (subject + details)

    redirect_to new_project_path(@project), :alert => e.message
  end

  def show
    if @project.contractor_recommendations.blank?
      arr_of_top_contractors = RecommendationManagementService.get_top_three_contractors_for_project(@project.id)
      RecommendationManagementService.persist_recommendations(arr_of_top_contractors, @project.id)
    end

    @project.reload
    @recommendations = @project.contractor_recommendations
  end

  def edit
  end

  def update
    validate_create_request

    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to edit_project_path(@project), notice: 'Project was successfully updated.' }
        format.json { render :json => @projects }
      else
        format.html { render :edit }
      end
    end

  rescue Exception => e
    subject = "Error: Exception in project#update. Msg => #{ e.message }."
    details = params.inspect
    logger.error (subject + details)

    redirect_to edit_project_path(@project), :alert => e.message
  end

  # todo:
  def update_recommendation
    @recommendation_id = params[:id].split('_').last

    @recommendation = ProjectContractorRelation.find(@recommendation_id)
    value_to_update = ActiveModel::Type::Boolean.new.cast(params[:value])

    if params[:id].include? 'project_owner_accepted'
      @recommendation.update_column(:project_owner_accepted, value_to_update)
    elsif params[:id].include? 'contractor_accepted'
      @recommendation.update_column(:contractor_accepted, value_to_update)
    end
  end


  private

  def validate_create_request
    ExceptionUtils.check_if(params[:project][:maximum_budget].to_i >= params[:project][:minimum_budget].to_i,
                            'Maximum budget cannot be less than minimum budget.')

    ExceptionUtils.check_if(params[:project][:design_services_needed] == '1' || params[:project][:build_services_needed] == '1',
                            'At-least one service should be chosen for the project.')

  end

  def set_project
    @project = Project.find(params[:id])
    raise Exception.new("Project with #{params[:id]} not found") if @project.nil?
  end

  def project_params
    params.require(:project).permit(:id, :name, :latitude, :longitude, :maximum_budget, :minimum_budget, :description, :design_services_needed,
                                    :build_services_needed
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contractor/contractor_helper.rb
module Contractor::ContractorHelper
end

app/helpers/contractor/general_contractors_helper.rb
module Contractor::GeneralContractorsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/contractor/general_contractors/_form.html.erb
<div class="form-padding" style="background: lightgrey;border: 1px solid bisque;">
  <%= form_for ([:contractor, @general_contractor]) do |f| %>
      <% if @general_contractor.errors.any? %>
          <div id="errors">
            <h2><%= pluralize(@general_contractor.errors.count, "error") %> prevented this post from saving:</h2>
            <ul>
              <% @general_contractor.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <div class="row">
        <div class="col-md-6" >

          <div class="form-group col-md-12">
            <%= f.label 'Contractor name', class: "required" %>
            <%= f.text_field :name , class: "form-control", required: true %>
          </div>

          <div class="form-group col-md-12">
            <%= f.label 'Contractor location latitude', class: "required" %>
            <%= f.text_field :latitude , class: "form-control", type: 'number', required: true, step: 'any' %>
          </div>

          <div class="form-group col-md-12">
            <%= f.label 'Contractor location longitude' , class: "required" %>
            <%= f.text_field :longitude, class: "form-control", type: 'number', required: true, step: 'any' %>
          </div>
        </div>
        <div class="col-md-6" >
          <div class="form-group col-md-12">
            <%= f.label :minimum_budget_willing, class: "required"  %>
            <%= f.text_field :minimum_budget_willing, class: "form-control", type: 'number', required: true %>
          </div>
          <div class="form-group col-md-12">
            <%= f.label :maximum_budget_willing, class: "required"  %>
            <%= f.text_field :maximum_budget_willing, class: "form-control", type: 'number', required: true %>
          </div>
          <div class="form-group col-md-12">
            <%= f.label 'Choose services offered'%><br>
            <%= f.check_box :design_services_offered %>
            <%= f.label :design_services_offered%>
            <br>
            <%= f.check_box :build_services_offered %>
            <%= f.label :build_services_offered%>

          </div>
          <div class="form-group col-md-12">
            <%= f.submit (@general_contractor.new_record? ? "Create" : "Update Contractor Details"), class: "btn btn-primary", style: "width: 100%;" %>
          </div>
        </div>
      </div>
  <% end %>
</div>
<style>
  label.required:after{content:"*"}
</style>

app/views/contractor/general_contractors/edit.html.erb
<%= render partial: 'form'%>
<hr style="color: grey">

app/views/contractor/general_contractors/index.html.erb
<a href="<%=new_contractor_general_contractor_path %>" class="btn btn-success">Create New Contractor</a>

<hr>
<h4>Log in using your existing contractor id.</h4>
<br>
<span style="font-size: 12px; color: red; ">(Note: the website is in beta phase with authentication disabled)</span>

<div class="row" style="padding:0px 15px;">
  <table class="table table-hover" style="border-spacing: 0px 6px;border-collapse: separate;">
    <thead>
    <tr style="background-color: white;">
      <th> Id </th>
      <th>Contractor Name</th>
      <th>Actions</th>
    </tr>
    </thead>

    <tbody>
    <% @general_contractors.each do |gc| %>
        <tr>
          <td><%= gc&.id%></td>
          <td><%= gc&.name %></td>
          <td>
            <a href="<%=contractor_general_contractor_path(gc) %>" class="btn btn-primary"> Log in</a>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/contractor/general_contractors/new.html.erb
<%= render partial: 'form'%>

app/views/contractor/general_contractors/show.html.erb
<h3> Contractor Details</h3>

<table class="table table-bordered">
  <tr>
    <th>Project Name:</th>
    <td><%= @general_contractor.name %></td>
  </tr>
  <tr>
    <th>Budget Range</th>
    <td>
      <%= @general_contractor.minimum_budget_willing %> $ -
      <%= @general_contractor.maximum_budget_willing %> $
    </td>
  </tr>
  <tr>
    <th>Location (lat,long)</th>
    <td>
      <%= @general_contractor.latitude %>,
      <%= @general_contractor.longitude %>
    </td>
  </tr>
  <tr>
    <th>Design Services Offered </th>
    <td> <%= @general_contractor.design_services_offered %></td>
  </tr>
  <tr>
    <th>Build Services Offered </th>
    <td> <%= @general_contractor.build_services_offered %></td>
  </tr>

</table>
<div class="row" style="padding:0px 15px;">
  <h3> Recommended Projects</h3>
  <table class="table table-hover" style="border-spacing: 0px 6px;border-collapse: separate;">
    <thead>
    <tr style="background-color: white;">
      <th> Id </th>
      <th>Name</th>
      <th>Price Range (in $)</th>
      <th>Location(LAT-LONG)</th>
      <th> Description</th>
      <th>Score</th>
      <th>Distance in Kms</th>
      <th>Project Owner Response</th>
      <th>Contractors Response</th>
      <th>Status</th>
    </tr>
    </thead>

    <tbody>
    <% @project_recommended.each do |pr| %>
        <tr>
          <td><%= pr&.project&.id%></td>
          <td><%= pr&.project&.name %></td>
          <td><%= pr&.project&.minimum_budget %> $ - <%= pr&.project&.maximum_budget %> $</td>
          <td><%= pr&.project&.latitude %> - <%= pr&.project&.longitude %> </td>
          <td><%= pr&.project&.description %></td>
          <td><%= pr&.score %></td>
          <td><%= pr&.distance %></td>
          <td>
            <%= if pr.project_owner_accepted
                  'Yes'
                else
                  pr.project_owner_accepted.nil? ? 'Awaited' : 'No'
                end %>
          </td>
          <td>
            <label>Yes</label><input type="radio" name="contractor_accepted_<%= pr.id %>" id="contractor_accepted_true_<%=pr.id %>" value="true" <%= pr.contractor_accepted == true ? 'checked="checked"' : '' %> >
            <label>No</label><input type="radio" name="contractor_accepted_<%= pr.id %>" id="contractor_accepted_false_<%=pr.id %>" value="false" <%= pr.contractor_accepted == false ? 'checked="checked"' :'' %>  >
          </td>
          <td id="status_<%= pr.id %>">
            <%= render partial: 'projects/recommendation_status', locals: {recommendation: pr}  %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <p>
    <h4>Score calculation</h4>
    <strong>Score value 3:</strong><br>
    Best match. Contractor budget is subset of project budget. The project owner is most likely to accept this contractor.<br>
    Eg: Project budget 100$ - 200$ and contractor budget 120$ - 160$<br><br>

    <strong>Score value 2:</strong><br>
    Project budget is subset of contractor budget.<br>
    Eg: Project budget 100$ - 200$ and contractor budget 80$ - 700$<br><br>

    <strong>Score value 1:</strong><br>
    Some overlap in budgets.<br>
    Eg: Project budget 100$ - 200$ and contractor budget 180$ - 700$<br><br>

    <strong>Score value 0:</strong><br>
    No overlap in budgets. Very rarely but if no matching contractors are their then project owners may choose contractors with score value of 0.<br>
    Eg: Project budget 100$ - 200$ and contractor budget 500$ - 700$<br>
  </p>
</div>

<script>
  $('input[type=radio]').change(function() {
    $.ajax( { type: 'POST', url: "/update_recommendation?value="+this.value+"&id="+ this.name })
  });
</script>

app/views/layouts/_flash_messages.html.erb
<% if flash.alert.present? %>
    <div class="alert alert-danger alert-dismissible" role="alert" style="font-weight: 500">
      <%= flash.alert %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
<% end %>
<% if flash.notice.present? %>
    <div class="alert alert-success alert-dismissible" role="alert" style="font-weight: 500">
      <%= flash.notice %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sweeten for Home Owners</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body style="background-color: #e6e6e6">
<header class="navbar navbar-default" role="navigation" style="background-color: #6747b1; color: white">
  <div class="navbar-inner">
    <div class="container">

      <div class="navbar-brand"><%= link_to "Sweeten for Home Owners", root_path, style: "color: #c0dbe0" %></div>
      <nav class="collapse navbar-collapse navbar-ex1-collapse">
        <!--user login-->
        <div class="dropdown" style="float: right;margin-top: 15px;">
          <span>Switch Persona</span>
          <div class="dropdown-content">
            <ul>
              <li><%= link_to 'Access as Contractor', contractor_general_contractors_path %></li>
              <li><%= link_to 'Access as Home Owner', root_path %></li>
            </ul>
          </div>
        </div>
      </nav>

    </div>
  </div>
</header>

<!--flash message-->
<div id="main_content" class="container">

  <%= render partial: 'layouts/flash_messages' %>

  <div id="content" class="col-md-9 center-block">
    <%= yield %>
  </div>
</div>
</div>
</body>
</html>

<style>
  .dropdown {
    position: relative;
    display: inline-block;
  }

  .dropdown-content {
    display: none;
    position: absolute;
    background-color: #f9f9f9;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    padding: 12px 16px;
    z-index: 1;
  }
  .dropdown-content a {
    text-decoration: none;
  }

  .dropdown:hover .dropdown-content {
    display: block;
  }
</style>

app/views/layouts/contractor_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sweeten for Contractors</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'contractor', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'contractor', 'data-turbolinks-track': 'reload' %>
</head>

<body class="contractor_view">
<header class="navbar navbar-default" style="background-color: #fffb7b" role="navigation">
  <div class="navbar-inner">
    <div class="container">
      <div class="navbar-brand"><%= link_to "Sweeten for Contractors", contractor_general_contractors_path %></div>
      <nav class="collapse navbar-collapse navbar-ex1-collapse">
        <!--user login-->
        <div class="dropdown" style="float: right;margin-top: 15px;">
          <span>Switch Persona</span>
          <div class="dropdown-content">
            <ul>
              <li><%= link_to 'Access as Contractor', contractor_general_contractors_path %></li>
              <li><%= link_to 'Access as Home Owner', root_path %></li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </div>
</header>
<!--flash message-->
<div id="main_content" class="container">

  <%= render partial: 'layouts/flash_messages' %>

  <div id="content" class="col-md-9 center-block">
    <%= yield %>
  </div>
</div>
</div>
</body>
</html>

<style>
  .contractor_view {
    background-color: #d7d8b3;
  }

  .dropdown {
    position: relative;
    display: inline-block;
  }

  .dropdown-content {
    display: none;
    position: absolute;
    background-color: #f9f9f9;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
    padding: 12px 16px;
    z-index: 1;
  }

  .dropdown-content a {
    text-decoration: none;
  }

  .dropdown:hover .dropdown-content {
    display: block;
  }
</style>

app/views/projects/_form.html.erb
<div class="form-padding" style="background: beige;border: 1px solid bisque;">
  <%= form_for @project do |f| %>
      <% if @project.errors.any? %>
          <div id="errors">
            <h2><%= pluralize(@project.errors.count, "error") %> prevented this post from saving:</h2>
            <ul>
              <% @project.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <div class="row">
        <div class="col-md-6" >

          <div class="form-group col-md-12">
            <%= f.label 'Project Name', class: "required" %>
            <%= f.text_field :name , class: "form-control", required: true %>
          </div>


          <div class="form-group col-md-12">
            <%= f.label "Minimum Budget (in $)", class: "required"  %>
            <%= f.text_field :minimum_budget, class: "form-control", type: 'number', required: true %>
          </div>
          <div class="form-group col-md-12">
            <%= f.label "Maximum Budget (in $)", class: "required"  %>
            <%= f.text_field :maximum_budget, class: "form-control", type: 'number', required: true %>
          </div>
          <div class="form-group col-md-12">
            <%= f.label 'Project location latitude', class: "required" %>
            <%= f.text_field :latitude , class: "form-control", type: 'number', required: true, step: 'any' %>
          </div>

          <div class="form-group col-md-12">
            <%= f.label 'Project location longitude' , class: "required" %>
            <%= f.text_field :longitude, class: "form-control", type: 'number', required: true, step: 'any' %>
          </div>
        </div>
        <div class="col-md-6" >

          <div class="form-group col-md-12">
            <%= f.label :description %>
            <%= f.text_field :description, class: "form-control" , style: "height: 158px;"%>
          </div>


          <div class="form-group col-md-12">
            <strong>Choose services needed </strong><br><br>
            <%= f.check_box :design_services_needed %>
            <%= f.label :design_services%><br>

            <%= f.check_box :build_services_needed %>
            <%= f.label :build_services%>
          </div>
          <div class="form-group col-md-12">
            <%= f.submit (@project.new_record? ? "Create Project" : "Update Project"), class: "btn btn-primary", style: "width: 100%;" %>
          </div>
        </div>
      </div>
  <% end %>
</div>
<style>
  label.required:after{content:"*"}
</style>

app/views/projects/_recommendation_status.html.erb
<% if (recommendation.contractor_accepted) && (recommendation.project_owner_accepted) %>
    <p style="color: green"> Match Found</p>
<% elsif recommendation.contractor_accepted == false && !recommendation.project_owner_accepted == false%>
    <p style="color: red"> Rejected by Both</p>
<% elsif (recommendation.contractor_accepted == nil) || (recommendation.project_owner_accepted == nil) %>
    <p style="color: blueviolet">Pending</p>
<% elsif recommendation.contractor_accepted == false %>
    <p style="color: red"> Rejected by Contractor </p>
<% elsif recommendation.project_owner_accepted == false %>
    <p style="color: red"> Rejected by Owner </p>

<% end %>

app/views/projects/edit.html.erb
<%= render partial: 'form' %>
<hr style="color: grey">

app/views/projects/index.html.erb
<div class="row" style="padding:0px 15px;">
  <a href="<%=new_project_path %>" class="btn btn-success">Create New Renovation Project</a>
  <hr>
  <h4>Log in to your existing Renovation project.</h4>
  <br>
  <span style="font-size: 12px; color: red; ">(Note: the website is in beta phase with authentication disabled)</span>

  <table class="table table-hover" style="border-spacing: 0px 6px;border-collapse: separate;">
    <thead>
    <tr style="background-color: white;">
      <th> Id </th>
      <th>Project Name</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
    </thead>

    <tbody>
    <% @projects.each do |project| %>
        <tr>
          <td><%= project&.id%></td>
          <td><%= project&.name %></td>
          <td><%= project&.description %></td>
          <td>
            <a href="<%= project_path(project) %>" class="btn btn-primary"> Log In</a>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/projects/new.html.erb
<%= render partial: 'form' %>

app/views/projects/show.html.erb
<h3> Project Details</h3>

<table class="table table-bordered">
  <tr>
    <th>Project Name:</th>
    <td><%= @project.name %></td>
  </tr>
  <tr>
    <th>Budget Range</th>
    <td>
      <%= @project.minimum_budget %> $ -
      <%= @project.maximum_budget %> $
    </td>
  </tr>
  <tr>
    <th>Location (lat,long)</th>
    <td>
      <%= @project.latitude %>,
      <%= @project.longitude %>
    </td>
  </tr>
  <tr>
    <th>Design Services Needed </th>
    <td> <%= @project.design_services_needed %></td>
  </tr>
  <tr>
    <th>Build Services Needed </th>
    <td> <%= @project.build_services_needed %></td>
  </tr>

</table>
<div class="row" style="padding:0px 15px;">
  <h3> Recommended Contractors</h3>
  <table class="table table-hover" style="border-spacing: 0px 6px;border-collapse: separate;">
    <thead>
    <tr style="background-color: white;">
      <th> Id </th>
      <th>Contractor Name</th>
      <th>Price Range (in $)</th>
      <th>Location (lat, long)</th>
      <th>Score</th>
      <th>Distance in Kms</th>
      <th>Project Owner Response</th>
      <th>Contractors Response</th>
      <th>Status</th>
    </tr>
    </thead>

    <tbody>
    <% @recommendations.each do |recommendation| %>
        <tr>
          <td><%= recommendation&.general_contractor&.id%></td>
          <td><%= recommendation&.general_contractor&.name %></td>
          <td><%= recommendation&.general_contractor&.minimum_budget_willing %> $ - <%= recommendation&.general_contractor&.maximum_budget_willing %> $</td>
          <td><%= recommendation&.general_contractor&.latitude %>, <%= recommendation&.general_contractor&.longitude %></td>
          <td><%= recommendation&.score %></td>
          <td><%= recommendation&.distance %></td>
          <td>
            <input type="radio" name="project_owner_accepted_<%= recommendation.id %>" id="project_owner_accepted_true_<%= recommendation.id %>" value="true" <%= recommendation.project_owner_accepted == true ? 'checked="checked"' : '' %> > <label for="project_owner_accepted_true_<%= recommendation.id %>">Yes</label> <br>
            <input type="radio" name="project_owner_accepted_<%= recommendation.id %>" id="project_owner_accepted_false_<%= recommendation.id %>" value="false" <%= recommendation.project_owner_accepted == false ? 'checked="checked"' : '' %> > <label for="project_owner_accepted_false_<%= recommendation.id %>">No</label>
          </td>
          <td>
            <%= if recommendation.contractor_accepted
                  'Yes'
                else
                  recommendation.contractor_accepted.nil? ? 'Awaited' : 'No'
                end %>
          </td>
          <td id="status_<%= recommendation.id %>">
            <%= render partial: 'recommendation_status', locals: {recommendation: recommendation}  %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <p>
  <h4>Score calculation</h4>
  <strong>Score value 3:</strong><br>
  Best match. Contractor budget is subset of project budget. The project owner is most likely to accept this contractor.<br>
  Eg: Project budget 100$ - 200$ and contractor budget 120$ - 160$<br><br>

  <strong>Score value 2:</strong><br>
  Project budget is subset of contractor budget.<br>
  Eg: Project budget 100$ - 200$ and contractor budget 80$ - 700$<br><br>

  <strong>Score value 1:</strong><br>
  Some overlap in budgets.<br>
  Eg: Project budget 100$ - 200$ and contractor budget 180$ - 700$<br><br>

  <strong>Score value 0:</strong><br>
  No overlap in budgets. Very rarely but if no matching contractors are their then project owners may choose contractors with score value of 0.<br>
  Eg: Project budget 100$ - 200$ and contractor budget 500$ - 700$<br>
  </p>
</div>

<script>
  $('input[type=radio]').change(function() {
    $.ajax( { type: 'POST', url: "/update_recommendation?value="+this.value+"&id="+ this.name })
  });
</script>

app/views/projects/update_recommendation.js.erb
<% if ((@recommendation.contractor_accepted == true) && ( @recommendation.project_owner_accepted == true ) ) %>
    $('#status_<%= @recommendation_id%>').empty();
    $('#status_<%= @recommendation_id%>').html('<p style = "color: green" > Match Found </p>');

<% elsif !@recommendation.contractor_accepted && !@recommendation.project_owner_accepted%>
$('#status_<%= @recommendation_id%>').empty();
$('#status_<%= @recommendation_id%>').html('<p style = "color: red" > Rejected by Both</p>');

<% elsif ((@recommendation.contractor_accepted == nil) || ( @recommendation.project_owner_accepted == nil ) ) %>
$('#status_<%= @recommendation_id%>').empty();
$('#status_<%= @recommendation_id%>').html('<p style = "color:blueviolet" > Pending </p>');

<% elsif ((@recommendation.contractor_accepted == false)) %>
  $('#status_<%= @recommendation_id%>').empty();
  $('#status_<%= @recommendation_id%>').html('<p style = "color: red" > Rejected by Contracter</p>');

<% elsif (( @recommendation.project_owner_accepted == false )) %>
  $('#status_<%= @recommendation_id%>').empty();
  $('#status_<%= @recommendation_id%>').html('<p style = "color: red" > Rejected by Project Owner</p>');

<% end %>